    .text

    .globl __symver_lzma_stream_encoder_mt_XZ_5_1_2alpha
    .set __symver_lzma_stream_encoder_mt_XZ_5_1_2alpha, lzma_stream_encoder_mt
    .symver __symver_lzma_stream_encoder_mt_XZ_5_1_2alpha, lzma_stream_encoder_mt@XZ_5.1.2alpha

    .globl __symver_lzma_stream_encoder_mt_memusage_XZ_5_1_2alpha
    .set __symver_lzma_stream_encoder_mt_memusage_XZ_5_1_2alpha, lzma_stream_encoder_mt_memusage
    .symver __symver_lzma_stream_encoder_mt_memusage_XZ_5_1_2alpha, lzma_stream_encoder_mt_memusage@XZ_5.1.2alpha

    .globl __symver_lzma_block_uncomp_encode_XZ_5_2_2
    .set __symver_lzma_block_uncomp_encode_XZ_5_2_2, lzma_block_uncomp_encode
    .symver __symver_lzma_block_uncomp_encode_XZ_5_2_2, lzma_block_uncomp_encode@XZ_5.2.2

    .globl __symver_lzma_cputhreads_XZ_5_2_2
    .set __symver_lzma_cputhreads_XZ_5_2_2, lzma_cputhreads
    .symver __symver_lzma_cputhreads_XZ_5_2_2, lzma_cputhreads@XZ_5.2.2

    .globl __symver_lzma_get_progress_XZ_5_2_2
    .set __symver_lzma_get_progress_XZ_5_2_2, lzma_get_progress
    .symver __symver_lzma_get_progress_XZ_5_2_2, lzma_get_progress@XZ_5.2.2

    .globl __symver_lzma_stream_encoder_mt_XZ_5_2_2
    .set __symver_lzma_stream_encoder_mt_XZ_5_2_2, lzma_stream_encoder_mt
    .symver __symver_lzma_stream_encoder_mt_XZ_5_2_2, lzma_stream_encoder_mt@XZ_5.2.2

    .globl __symver_lzma_stream_encoder_mt_memusage_XZ_5_2_2
    .set __symver_lzma_stream_encoder_mt_memusage_XZ_5_2_2, lzma_stream_encoder_mt_memusage
    .symver __symver_lzma_stream_encoder_mt_memusage_XZ_5_2_2, lzma_stream_encoder_mt_memusage@XZ_5.2.2

    .section .note.GNU-stack,"",@progbits
